### ISSUE TITLE
Image Export Not Working?

### ISSUE THREAD

**Issue by HeroMines** [playest/hextml#1]
Whenever I export my image it comes out messed up.
![hmmm 2018-07-07t05_32_02 374z](https://user-images.githubusercontent.com/22183857/42407309-a694d61e-8187-11e8-87cf-a312e2e59158.png)

**Comment by Caddzilla** [comment]
I also keep encountering this issue. It doesn't matter how old or new the file that I export is, it always comes out in some variant of this.
![world of exa of mple 2018-07-15t10_40_55 697z](https://user-images.githubusercontent.com/41262017/42733258-3f8e0896-8826-11e8-8943-71bc02bddfca.png)

**Comment by playest** [comment]
Have you tried using a different browser? What browser (with version number) are you using? Could you attach your HTML save file to the issue?

**Comment by playest** [comment]
It seems that it's a problem that occurs only with the chrome browser. I'll try to find a workaround but in the mean time you can switch to firefox when you export as an image.

**Comment by Caddzilla** [comment]
okay thanks, I'm using a chromebook so unfortunately there's nothing
directly I can export with. But I'm in no major rush, everything else has
worked fine on the website.
