### ISSUE TITLE
unable to load in older project

### ISSUE THREAD

**Issue by Foxxxiecoxxxie** [playest/hextml#2]
Hello,

I was using your hex map maker a few months ago and really enjoyed it. I went to make some additions and I am now unable to access my local save or find a way to tell it to open it. Any suggestions for what it might be?

Thank you for the tool though, it's an excellent program either way

**Comment by playest** [comment]
Do you remember the name of you map? Your account's email could also help me find it.

**Comment by Foxxxiecoxxxie** [comment]
Hello,

I believe I named it cloudscape. The email address should be
cyberdemon4377@gmail.com.

I also have an html local save on my desktop, but it doesn't open.

Thank you for your help

**Comment by playest** [comment]
I'll look into it as soon as possible. Could you attach your local html save to the issue please?

**Comment by Foxxxiecoxxxie** [comment]
Thank you very much for your assistance

**Comment by playest** [comment]
I found your map! Here it is. It open on my computer, tell me if if doesn't on yours. Happy DMing :)
[map.zip](https://github.com/playest/hextml/files/2363315/map.zip)
