### ISSUE TITLE
Unable to export map as image

### ISSUE THREAD

**Issue by Supermanxtu4** [playest/hextml#4]
when i try to export my world map as an image, it will begin loading like normal but taking longer than usual, and then at the end it doesn't save or give me a prompt to save file or anything. My map is 121w 59l so it could be size related but is there anything else i could do? I'm in Firefox, and everything else works fine. I can still edit, save, and open, just not export as image.

**Comment by playest** [comment]
I fear this is size related and I don't really know what can be done about that. You could try using Firefox Screenshots (https://support.mozilla.org/en-US/kb/firefox-screenshots).

**Comment by Supermanxtu4** [comment]
i restarted my computer and i finally got it to save as a picture, but im definitely pushing the limits lol

**Comment by ChipmunkWrangler** [comment]
If I try to export a map (for example, the tutorial map), I end up with a what seems to be a blank png of the right dimensions. The image data isn't all zeroes, though. I'm using OSX
 + Firefox.

![Tutorial Five 2019-09-06T05_38_09 600Z](https://user-images.githubusercontent.com/9989349/64406636-d1211980-d071-11e9-985f-8ebccbde0818.png)
