### ISSUE TITLE
Paintbrush adds new hex line/column.

### ISSUE THREAD

**Issue by Josecouves** [playest/hextml#5]
Hello, I'm not sure if this is the correct place to post something like this and I apologize if it's not.

In the previous version of Hextml hex height and width would not change unless configurated in the map settings tab.  However, in this version it seems to add a line/column each time I click on any edge of it when trying to add or remove something with the paintbrush tool.

I'm just wondering if there is some option to lock the height and width of the hex map that I have missed in the tutorial or if this functionality could possibly be added in the future.

I thank you for making this great tool and I once again apologize if this isn't the correct place to ask something like this.

Have a wonderful day!

**Comment by playest** [comment]
This is an appropriate place for such a message :)
There is not way to "lock" the size for now but I'll add it to the list of features for the next version.
Have a nice day!
