### ISSUE TITLE
In Text/Secret Notes, applying bullet style doesn't allow text input

### ISSUE THREAD

**Issue by horusofoz** [playest/hextml#6]
**Problem:**
In any hex, adding bullets on a line without first entering text prevents text input.

**Workaround:**
Input first bullet point then apply bullet style to the line.

**Browser:** Firefox 80.0.1 (64-bit)
**OS:** Windows 10.0.18363

**Comment by playest** [comment]
I fixed by updating the editor to the last version. Thank you for reporting this.
